services:
  - type: web
    name: instagram-clone-api
    runtime: node
    buildCommand: npm ci --workspace=server --workspace=shared --include-workspace-root=false && npm run build:server
    startCommand: npm run start:server
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_SECRET_KEYE
        sync: false
